### ISSUE TITLE
Pivot Control - SelectedIndex/Item attributes are not working

### ISSUE THREAD

**Issue by P4trik** [winjs/angular-winjs#54] opened 2015-07-30 13:27 UTC
If I declare the "selected-index" property of the win-pivot control, nothing is happen. 
Maybe I use it in a wrong manner.  A more detailed documentation or examples would be nice.

`<win-pivot selected-index='1'>
                win-pivot-item header="'Header1'">Item1</win-pivot-item>
                win-pivot-item header="'Header2'">Item2</win-pivot-item>
</win-pivot>`

Best regards

**Comment by AmazingJaze** [comment] 2015-08-21 02:33
Hi @P4trik , thanks for reporting this, It looks like a duplicate of the same behavior that was called out more generally in #45.
If you would like to help us improve the angular-winjs adapter better faster, we are actively encouraging pull requests for issues like these.

**Closed** 2015-09-08 20:01 UTC
Labels: .kind: question, feature: pivot

**Comment by sondreb** [comment] 2015-10-19 18:15
Which commit fixes the binding of selected-index and selected-item on the pivot control? Appears both this and #45 are closed, though I can't see any commits that have changed the code in the repo for 2 months?

My workaround for now:

```javascript
$scope.selectedItem = null;
$scope.selectedIndex = -1;

$scope.tabChanged = function () {
    var tabProfileElement = document.getElementById('tabProfile');
    $scope.selectedIndex = tabProfileElement.winControl.selectedIndex;
    $scope.selectedItem = tabProfileElement.winControl.selectedItem;
};
```
Markup:
```html
<win-pivot id="tabProfile" on-selection-changed="tabChanged()">
```
