### ISSUE TITLE
appBarCommands in the section='secondary' do not update the correct element for disabled=true/false

### ISSUE THREAD

**Issue by mtycholaz** [winjs/angular-winjs#14] opened 2015-03-29 06:06 UTC
I have a button in my appbar that I want to disable based on a value on my scope. The binding is working, and it sets the value on the control correctly (verified by debugging). However, it's not updating the correct button element. If you look at the screenshot below, you'll notice that there are two buttons for the save. One in the `win-toolbar-actionarea` and one in the `win-toolbar-overflowarea`. The button that is displayed is within the `win-toolbar-overflowarea` (since my section is set to 'secondary'), but when Angular binding updates the disabled value on the control, the other button is updated instead. This is why you can see in the picture that one of the buttons is disabled, whereas the other is not. 

![image](https://cloud.githubusercontent.com/assets/3585379/6884292/bb57a170-d5a6-11e4-9bcc-271fd3a76d83.png)

Perhaps there is a quick and cheap fix for this? Maybe calling a WinJs function outside of Angular to process the change to make both elements match?

**Comment by AmazingJaze** [comment] 2015-03-29 09:34
Thanks for the bug. I believe this a dupe of https://github.com/winjs/winjs/issues/841
As an implementation detail the AppBar and ToolBar currently store all of their commands in the action-area element, and project copies of both secondary commands, and overflowing primary commands into the overflow area, while hiding the HTML of the original command, still residing in the action area. 

The correct pattern for updating commands in the AppBar and ToolBar should be to always update the wincontrol property of the original command, regardless of whether or not that command is currently visible in the actionarea or as a projection in the overflowarea.

Unfortunately because of this bug, no property changes on the AppBarCommands are being updated to their projections in the overflowarea.  

As a temporary workaround you can force the property updates to display on the projected command if you use the AppBar.showCommands() API and pass in the id of the command you want to update.

``` body.querySelector(".win-appbar").winControl.showCommands("a") ```

**Comment by rigdern** [comment] 2015-04-06 18:36
Closing due to inactivity.

**Closed by rigdern** 2015-04-06 18:36 UTC
